name: Wyckoff Scanner
on:
  schedule:
    - cron: "0 8 * * *"  # 8 AM UTC daily
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          mkdir -p data
          
      - name: Run Wyckoff Scanner
        env:
          GSHEETS_CREDS: ${{ secrets.GSHEETS_CREDS }}
        run: |
          python scripts/main.py
          python scripts/gsheets.py
